# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Oladipo Planet
subtitle: 无知和弱小不是生存的障碍,傲慢才是
email: pan49@126.com
description: iOS Developer working in ShangHai,China
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://drinking.github.io" # the base hostname & protocol for your site
twitter_username: Crazy_Drinking
github_username:  drinking

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
github: https://github.com/drinking